### ISSUE TITLE
Working in Arch Linux and Windows 10

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QEdit#14]
Hello!

I hope you had a happy holiday!

I've been fooling around with this, and I've got it working (on a basic level, at least).  I've tested it in Linux and Windows 10, and it seems to be working pretty well.

I fixed quite a few things, and I failed to take notes while doing so, but it's easy to see if you load the diff.

https://github.com/KVonGit/QEdit

The main thing was changing the way it named folders.  (See [this](https://github.com/KVonGit/QEdit/wiki/Delete-folder-with-dot-at-the-end-of-its-name-in-Windows) if you have folders with a "." at the end of the name in Windows that you can't delete, but be warned: I only found a way to delete the whole folder that contains said folders and it will NOT ask if you're sure first.)

Then, I changed it the way it found the input directory (and files) while copying files.  Then, I changed the way it found the file path to load a game.

Amazingly, I'm pretty sure I got all of that working.

I also added all the missing "lib" files (and such) to the "jsquest" directory.  So, you can scroll past most of the stuff at the beginning of the diff because it displays some of that code.

---
I've got a sad excuse for a change log / TODO list going on here: https://github.com/KVonGit/QEdit/issues/1

---
All I've done in a new game so far is:
- Add a description to the lounge
- Add an item to the lounge
- Add an examine property (text) to the item.

That all works in the compiled game!  Yippee!

Next, I'm adding a new room and an exit.  More on this as it comes in . . .

---
PS

Is what you've got on GitHub right now working on your end?  (I just realized I might be fixing stuff you've already fixed.)

**Comment by KVonGit** [comment]
UPDATE

I've got lots of stuff working now. I fixed the issue with autosave going crazy and freezing up the computer.  I've added the QuestJS v0.4 files.  It can successfully create multiple exits in rooms now.  (The [number 1 issue on my fork](https://github.com/KVonGit/QEdit/issues/1) lists much more.)

Right now, it looks like I need to be fixing the CSS stuff.  [CSS issue](https://github.com/KVonGit/QEdit/issues/3)

---
#### THINGS

- If you'd rather me not be fooling around with this (or if you realize that I'm just hacking away at bugs I find, not fully understanding what I'm doing, and would rather not use any of the code I'm adding/modifying), just say the word.  It would be completely understandable, and I'd stop adding things concerning this to your inbox(es).
- If you do want anything to do with my input on this one:
    - I question your sanity, sir.
    - I think I should probably find out how you'd like the CSS stuff to work before I do too much more coding.  I think I can use your ```parseStyle``` function to load the stuff from "assets/css/default.css".  I don't know that that is how you would handle that, though. (Note that I don't want to load *all* the stuff from the CSS file to the editor. I just want it to read the existing style sheet to load its current default values.  I am 99% sure I found an easy way to do it, too.)

**Comment by ThePix** [comment]
I have not done anything on this for several months, so any help you can give will be great. I am hoping QuestJS is more-or-less done - no more new features, just bug fixes - and I can look at this again in the new year. I am going to have to remind myself how it works first...

**Comment by ThePix** [comment]
The big thing I would like to do is integrate Blockly.
https://developers.google.com/blockly

I know Alex was looking at using Blockly, but no idea how far he got or how seriously he was considering it.

**Comment by KVonGit** [comment]
> The big thing I would like to do is integrate Blockly.

So, you want to add Blockly to what is currently there?  Like, so the user could do the puzzle pieces in one area of the window, and it puts the corresponding code into the input field?  (Just like that example in the link?)

I have nothing else to do today, besides find out how many of the CSS settings you'd like the editor to allow the user to access.  The editor can parse the date from an existing CSS sheet now.  All the editor is set up for is "main" and "side-panes".  I'm about to make sure this method will actually set the values of ```jsStyleSide_*``` stuff, and I bet it will.  If it does, I won't know what to do with "#main" as I don't see it in the new CSS stuff in v0.4.  (I think maybe I should use what is now in body instead of "main".)

I don't know if I can distract myself from this bit of code if the CSS settings I choose in the editor don't get appended to "default.css".  (I can append the file.  I learned how recently and tested it.)  I've pretty much got everything else I've tested working, besides bells and whistles like keyboard shortcuts and the like.

Anyway, I'm rambling on. I just posted new stuff to the [CSS issue](https://github.com/KVonGit/QEdit/issues/3).  I think you might (possibly) find it interesting.

I'll look at Blockly in between needing breaks from the CSS stuff, but I'm not familiar with it at all.  (I do like challenges, though.)

**Comment by ThePix** [comment]
In the Quest 5 editor you can switch below the GUI view and code view for each script. I would like that for the editor, using Blockly for the GUI view.

**Comment by KVonGit** [comment]
I got a test page to work fairly quickly.

It looks like the issue will be deciding which blocks are available to the user and when.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blockly Test</title>
    <script src="google-blockly-fd239e4/blockly_compressed.js"></script>
    <script src="google-blockly-fd239e4/blocks_compressed.js"></script>
    <script src="google-blockly-fd239e4/msg/js/en.js"></script>
    <script src="google-blockly-fd239e4/javascript_compressed.js"></script>

</head>
<body>
    <textarea id="textarea"></textarea>
    <div id="blocklyDiv" style="height: 480px; width: 600px;"></div>
    
    <xml id="toolbox" style="display: none">
        <block type="controls_if"></block>
        <block type="controls_repeat_ext"></block>
        <block type="logic_compare"></block>
        <block type="math_number"></block>
        <block type="math_arithmetic"></block>
        <block type="text"></block>
        <block type="text_print"></block>
        <block type="logic_boolean"></block>
      </xml>
      
</body>
<script>
    var workspace = Blockly.inject('blocklyDiv',
        {toolbox: document.getElementById('toolbox')});
    function myUpdateFunction(event) {
        var code = Blockly.JavaScript.workspaceToCode(workspace);
        document.getElementById('textarea').value = code;
        console.log(code);
    }
    workspace.addChangeListener(myUpdateFunction);

  </script>
  
</html>

```

---
![image](https://user-images.githubusercontent.com/30656341/103211908-143e7600-48cf-11eb-93b4-e43d31a64ffe.png)

---
http://media.textadventures.co.uk/games/bHj_DmWGzE_-qSvT0TzxXg/blocklytest.html

Setting that up took five minutes.

Deciding which blocks are available to use in the Quest editor and when?  Yeah.  That does not sound fun at all. Unless it was just all of them, like [this](https://blockly-demo.appspot.com/static/demos/code/index.html), but custom blocks would most definitely be necessary in Quest, too, I assume.

THOUGHTS
- I don't know if this falls within the scope of things I can pull off.
- To me (and I am admittedly old), the blocks are more of a pain in the butt than anything else.  Piecing them together takes me longer than just writing the code, and it seems that one would have to already know how to code before they would have any clue as to what to do with the blocks.  That's just the impression I got after fooling around with the blocks for five minutes or so.  I would opine that the menu system from Quest 5 looks much better and is probably much easier for the average Quest author to operate.  (I don't know, though.  It's just the first impression I got.)
- It might be much easier (and possibly more efficient?) to create a custom Blockly page and have it so the editor can open that in a window from which the code can be copied then pasted into the editor. Nah.  That's a bad idea.  Blockly will put the code in the text box as the puzzle is pieced together. Why make people copy and paste?  Hey...  I bet Blocky can be opened in its own window and still update the code in the text input box from its own window.  (That might be a good idea.  All those puzzle pieces probably get messy on-screen in a hurry.)
- Don't pay much attention to what I say about it because I'll subconsciously hate on Blockly until I'm no longer focused on getting the editor to do the CSS stuff correctly.  I'm pretty sure I've got everything else in the editor working enough to make functional games, although I haven't tested extensively.  It just ignores any CSS setting changes made in it (at the moment).  I am about to fix that after a short break.

**Comment by ThePix** [comment]
Can you get it into QEdit? That is where I failed....

**Comment by KVonGit** [comment]
> Can you get it into QEdit?

I'll try in an hour or so.

I have to figure out how to change ```jsStyleMain_color``` from json2js.js first.  I don't know how to access the variable to set the value.

**Comment by KVonGit** [comment]
UPDATE

I got the CSS stuff loading into the editor's default values.  Now I only have to make it append the CSS sheet during export to JS, and I've already had it doing that.  So, I should be bored soon and ready to try to get Blockly into the editor.

**Comment by KVonGit** [comment]
https://github.com/KVonGit/QEdit/issues/8

![image](https://user-images.githubusercontent.com/30656341/103257030-27942480-4955-11eb-9ade-773b972469f8.png)

**Comment by KVonGit** [comment]
> I installed [Blockly] via ```npm install blockly```. (I didn't have to fool with yarn. Maybe because I did it in Linux? Just a wild guess.)

This worked fine in Windows 10, too, just for the record's sake.

---
Closing this one out.
